---
title: "About Me"
---

I am currently a Manager of industry analysis and business intelligence for the Consumer Technology Association (CTA). My primary role for CTA is to oversee and manage our forecast data program. Using both internal and external data sets, I create various reports and analysis to help the industry in a variety of ways. I would consider myself an expert in how the technology industry/market is performing from a sales perpesctive and how emerging technologies and trends are impacting the industry.

I live in Fairfax, VA with my wonderful wife Courtney and our 3 incredibly cuddly and anxious animals. We have two dogs, Buddy and Maximus and a cat named Bentley.

I am an avid sports enthusiast and probably know the sports world more than I do the technology industry. My favorite sport to watch, talk, analyze and write about is football, but I really love all sports.

Analyzing and tracking data has always been a passion of mine and I incorporate it in everything that I do. From pacing and tracking my times training for triathlons to arguing about sports, I believe data is the key to everything.
