<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>STAT 515 Mid Project - FINAL PROJECT</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">STAT 515 Mid Project</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./original_graph.html"> 
<span class="menu-text">Original Graph</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./new_graphs.html"> 
<span class="menu-text">Redesigned Visuals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./video.html"> 
<span class="menu-text">Oral Presentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Final_KW.html" aria-current="page"> 
<span class="menu-text">Final Project</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Final_Report_Webpage.html"> 
<span class="menu-text">Code For Final Project</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#iii.-limitations" id="toc-iii.-limitations" class="nav-link active" data-scroll-target="#iii.-limitations">iii. Limitations</a></li>
  <li><a href="#iv.-conclusion" id="toc-iv.-conclusion" class="nav-link" data-scroll-target="#iv.-conclusion">iv. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">FINAL PROJECT</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="stat-515-final-project" class="level4">
<h4 class="anchored" data-anchor-id="stat-515-final-project"><strong>STAT 515 Final Project</strong></h4>
<p>Group Number: 2</p>
<p>Anusha Dusakanti, Kyle Wandel, Sumrah Shakeel</p>
</section>
<section id="abstract" class="level4">
<h4 class="anchored" data-anchor-id="abstract"><strong>Abstract</strong></h4>
<p>The aim of this research is to identify patterns and indicators that could potentially predict the signs of malignant cancerous cells. Through meticulous analysis, the paper investigates various aspects, including a deep dive into the predictor variables and their relationship to each other and the response variable, the creation of various statistical models to predict cancerous cells and then finally a comparison of models to choose the best one. By scrutinizing these factors, this research hopes to make discovering breast cancer in patients easier and earlier.</p>
</section>
<section id="i.-introduction" class="level4">
<h4 class="anchored" data-anchor-id="i.-introduction"><strong>I. Introduction</strong></h4>
<p>Among all cancers, breast cancer is one of the most prevalent worldwide. Even if the pharmaceutical sector has made significant investments in the search for a permanent cure for this cancer, it still raises the need for more analysis to be done on breast cancer data so that a cancerous tumor can be caught in the early stages.&nbsp;We intended to figure out whether distinct characteristics of the tumor cells may be used to predict the prospective appearance of breast cancer in females. With nine predictor variables and an outcome variable that would indicate whether the tumor is categorized as malignant (cancerous) or benign (non-cancerous), this dataset seemed promising.</p>
<p>The dataset we choose to perform this research is from Dr.&nbsp;William Wolberg and his clinical studies from 1989 to 1991. This dataset is very well known and highly integrable due to the amount of research conducted using this data. Below is a list and description of the 9 predictor variables and the 1 response variable (benormal).</p>
<ul>
<li><p><strong>clumpthickness</strong>: (1-10). Benign cells tend to be grouped in monolayers, while cancerous cells are often grouped in multilayers.</p></li>
<li><p><strong>uniformcellsize</strong> (1-10). Cancer cells tend to vary in size and shape.</p></li>
<li><p><strong>uniformcellshape</strong> (1-10). Cancer cells tend to vary in shape and size.</p></li>
<li><p><strong>margadhesion</strong>: (1-10). Normal cells tend to stick together, while cancer cells tend to lose this ability, so the loss of adhesion is a sign of malignancy.</p></li>
<li><p><strong>epithelial</strong>: (1-10). It is related to the uniformity mentioned above. Epithelial cells that are significantly enlarged may be malignant.</p></li>
<li><p><strong>barenuclei</strong>: (1-10). This term is used for nuclei not surrounded by cytoplasm (the rest of the cell). Those are typically seen in benign tumors.</p></li>
<li><p><strong>blandchromatin</strong>: (1-10). Describes a uniform “texture” of the nucleus seen in benign cells. In cancer cells, the chromatin tends to be more coarse and to form clumps.</p></li>
<li><p><strong>normalnucleoli</strong>: (1-10). Nucleoli are small structures seen in the nucleus. In normal cells, the nucleolus is usually very small, if visible. The nucleoli become more prominent in cancer cells, and sometimes there are multiple.</p></li>
<li><p><strong>mitoses</strong>: (1-10). Cancer is essentially a disease of uncontrolled mitosis.</p></li>
<li><p><strong>benormal</strong>: (2 or 4). Benign (non-cancerous) or malignant (cancerous) lump in a breast.</p></li>
</ul>
<p>The University of Wisconsin breast cancer data from William Wolberg has 699 observations and 10 variables, the first variable represents the ID of the sample and the last column “benornal” represents the classification/response variable (for benign, 4 for malignant).</p>
<pre><code>'data.frame':   699 obs. of  11 variables:
 $ id              : int  1000025 1002945 1015425 1016277 1017023 1017122 1018099 1018561 1033078 1033078 ...
 $ clumpthickness  : int  5 5 3 6 4 8 1 2 2 4 ...
 $ uniformcellsize : int  1 4 1 8 1 10 1 1 1 2 ...
 $ uniformcellshape: int  1 4 1 8 1 10 1 2 1 1 ...
 $ margadhesion    : int  1 5 1 1 3 8 1 1 1 1 ...
 $ epithelial      : int  2 7 2 3 2 7 2 2 2 2 ...
 $ barenuclei      : chr  "1" "10" "2" "4" ...
 $ blandchromatin  : int  3 3 3 3 3 9 3 3 1 2 ...
 $ normalnucleoli  : int  1 2 1 7 1 7 1 1 1 1 ...
 $ mitoses         : int  1 1 1 1 1 1 1 1 5 1 ...
 $ benormal        : int  2 2 2 2 2 4 2 2 2 2 ...</code></pre>
<p>Using this dataset we wanted to try and answer the following research questions:</p>
<p>Question 1: What are the variables displaying significant correlation?</p>
<p>Question 2: How does Principal Component Analysis contribute to understanding the variance explained by principal components in our dataset?</p>
<p>Question 3: Can a logistic regression model be created to accurately predict malignant breast cancer cells?</p>
<p>Question 4: Can a random forest model be created to accurately predict the likelihood of a cell being malignant?</p>
<p>To make the dataset ready for analysis we removed the ID column, checked and removed all rows with missing data changed he response variable values to malignant (4) = 1 and benign (2) = 0. After cleaning the dataset, we looked at a summary of the statistics for each variable. For our sample there are 444 records that are identified as not being malignant (=0) and 239 records that are identified as being malignant (=1).</p>
<pre><code> 0   1 
444 239 </code></pre>
<p>We next wanted to identify if there were any patterns among the predictor variables in the dataset. First we looked at the correlations, histograms and scatter plots of the variables using the pairs.panel() function.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="WhatsApp Image 2024-05-05 at 19.05.48.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Some of the variables showed correlations to each other, but none were deemed significant by the corr.test() function. But one thing we did notice was that many of the variables exhibited a right skew with their means larger than their medians. We could potentially log() the variables to make them more uniform.</p>
<p>Research questions</p>
</section>
<section id="ii.-materials-and-methods" class="level4">
<h4 class="anchored" data-anchor-id="ii.-materials-and-methods"><strong>II. Materials and Methods</strong></h4>
</section>
<section id="principal-component-analysis" class="level4">
<h4 class="anchored" data-anchor-id="principal-component-analysis">Principal Component Analysis</h4>
<p>As previously indicated, while there was some correlation between our variables, none of them was statistically significant. Additionally, some of the factors did not significantly connect with response variable prediction in some of our other models. In order to explore this further, we performed a principal component analysis on the predictor variables to determine whether accuracy naturally decreases when a dataset’s variable count is decreased, but not to an excessive degree.</p>
<p>We first took a look a the mean and variances of the variables in the dataset to see if the variables should be scaled or not. Below are the means an variances of the variables:</p>
<pre><code>Mean
clumpthickness  uniformcellsize uniformcellshape     margadhesion 
        4.442167         3.150805         3.215227         2.830161 
      epithelial       barenuclei   blandchromatin   normalnucleoli 
        3.234261         3.544656         3.445095         2.869693 
         mitoses         benormal 
        1.603221         1.349927 

Variance
clumpthickness  uniformcellsize uniformcellshape     margadhesion 
       7.9566944        9.3951130        8.9316153        8.2057165 
      epithelial       barenuclei   blandchromatin   normalnucleoli 
       4.9421089       13.2776950        6.0010133        9.3187722 
         mitoses         benormal 
       3.0021597        0.2278116 </code></pre>
<p>Based on these results the following variables exhibit some significant diversity across the dataset; clumpthickness, uniformcellsize, uniformcellshape, margadhesion, barenuclei and normalnucleoli. The following variables showed some moderate variability across the dataset; epithelial, blandchromatin, and mitoses. Because of these results it would be best to scale the variables for analysis.</p>
<p>After running a PCA analysis found that most of the variables are grouped indicating that there are similar observations based on the variable values. There are not too many outliers to indicate any unusual observations.</p>
<p>Looking at the bigplot mitoses has the largest contribution when looking at the variables to the corresponding principal component. All of the variables, except for mitoses are positively correlated. Most of the variables are closer to all the other variables except for mitoses, further indicating that they are strongly influenced by these corresponding variables. Looking at the axis’ of the graph PC1 explains the most variance in the data as it has the longer axis than PC2.</p>
<p><img src="Rplot.png" class="img-fluid"></p>
<p>The following graph is the scree plot for the PCA which is used to provide a simple yet effective way to see balance and the trade-off between retaining information and reducing dimensionality in your data. <img src="images/clipboard-172522986.png" class="img-fluid quarto-figure quarto-figure-center" width="530"> Looking at this graph we can easily identify that there is a large drop off-point after the first PCA, indicating that adding an additional principal component does not significantly add value at explaining the variability in the data.</p>
<p>The following graph shows cumulative proportion of variance that each principal components adds. <img src="images/clipboard-911580378.png" class="img-fluid quarto-figure quarto-figure-center" width="579"></p>
<p>Looking at this graph it seems that 4 principal components would be needed to explain over 80% of the variance.</p>
<p>The University of Wisconsin breast cancer data from William Wolberg has 699 observations and 10 variables, the first variable represents the ID of the sample and the last column “benormal” represents the classification/response variable (for benign, 4 for malignant).</p>
<p>To make the dataset ready for analysis we removed the ID column, checked and removed all rows with missing data changed the response variable values to malignant (4) = 1 and benign (2) = 0, then looked at summary statistics for each variable. For our sample there are 444 records that are identified as not being malignant (=0) and 239 records that are identified as being malignant (=1).</p>
<p>To identify if there were any patterns among the predictor variables in the dataset, first we looked at the correlations, histrograms and scatterplots of the variables using the pairs.panel() function.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-1001792189.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="720"></p>
</figure>
</div>
<p>Some of the variables showed correlations to each other, but none were deemed significant by the corr.test() function. We noticed many of the variables exhibited a right skew with their means larger than their medians. We could potentially log() the variables to make them more uniform.</p>
</section>
<section id="logistic-regression-model" class="level4">
<h4 class="anchored" data-anchor-id="logistic-regression-model">Logistic Regression Model</h4>
<p>We developed a logistic regression model to predict if a cell was cancerous or not. As our outcome can only be one of two things (cell is malignant or benign) we should be using a classification model and logistic regression is a simple model which is much easier to set up and train initially than other machine learning models.</p>
<p>For the first model we used the cleaned dataset and all of the variables.</p>
<p><strong>Logistic Regression Model 1-</strong></p>
<pre><code>Coefficients:
                  Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -10.10394    1.17488  -8.600  &lt; 2e-16 ***
clumpthickness     0.53501    0.14202   3.767 0.000165 ***
uniformcellsize   -0.00628    0.20908  -0.030 0.976039    
uniformcellshape   0.32271    0.23060   1.399 0.161688    
margadhesion       0.33064    0.12345   2.678 0.007400 ** 
epithelial         0.09663    0.15659   0.617 0.537159    
barenuclei         0.38303    0.09384   4.082 4.47e-05 ***
blandchromatin     0.44719    0.17138   2.609 0.009073 ** 
normalnucleoli     0.21303    0.11287   1.887 0.059115 .  
mitoses            0.53484    0.32877   1.627 0.103788    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 884.35  on 682  degrees of freedom
Residual deviance: 102.89  on 673  degrees of freedom
AIC: 122.89</code></pre>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Log1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>In this model the variables clumpthickness, margadhesion, barenuclei, blandchromatin were considered the only variables had a significant impact on the response variables with p-values less than 0.5. The overall model had an AIC of 122.89.</p>
<p>Further, we created a new model after logging our variables. For this model the variables clumpthickness and barenuclei were considered the only variables that had a significant impact on the response variables with p-values less than 0.5. The overall model had an AIC of 127.02.</p>
<p><strong>Logisitic Regression Model 2-</strong></p>
<pre><code>Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)      -9.31304    1.25953  -7.394 1.42e-13 ***
clumpthickness    1.80864    0.59805   3.024  0.00249 ** 
uniformcellsize   0.50056    0.66380   0.754  0.45080    
uniformcellshape  1.26038    0.74379   1.695  0.09016 .  
margadhesion      0.71750    0.39504   1.816  0.06933 .  
epithelial       -0.04541    0.63630  -0.071  0.94310    
barenuclei        0.36117    0.09149   3.948 7.89e-05 ***
blandchromatin    1.49565    0.61321   2.439  0.01473 *  
normalnucleoli    0.48867    0.35560   1.374  0.16938    
mitoses           1.34541    0.74040   1.817  0.06920 .  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 884.35  on 682  degrees of freedom
Residual deviance: 107.02  on 673  degrees of freedom
AIC: 127.02

Number of Fisher Scoring iterations: 8</code></pre>
<p><img src="log2.png" class="img-fluid"></p>
<p>Based on the AIC of these two models, the non-logged model performed better. Then we simplified the model.&nbsp;</p>
<p><strong>Logisitic Regression Model 3-</strong></p>
<pre><code>Coefficients:
                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)    -10.11370    1.03264  -9.794  &lt; 2e-16 ***
clumpthickness   0.81166    0.12585   6.450 1.12e-10 ***
margadhesion     0.43412    0.11403   3.807 0.000141 ***
barenuclei       0.48136    0.08816   5.460 4.76e-08 ***
blandchromatin   0.70154    0.15196   4.616 3.90e-06 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 884.35  on 682  degrees of freedom
Residual deviance: 125.77  on 678  degrees of freedom
AIC: 135.77

Number of Fisher Scoring iterations: 8</code></pre>
<p><img src="log3.png" class="img-fluid"></p>
<p>As could be predicted, the model that included only the significant variables was worse at explaining the dataset. The complex model is definitely better than the simpler model, as demonstrated by the results of the Chisq test.</p>
<pre><code>Coefficients:
   (Intercept)  clumpthickness    margadhesion      barenuclei  blandchromatin  
      -10.1137          0.8117          0.4341          0.4814          0.7015  

Degrees of Freedom: 682 Total (i.e. Null);  678 Residual
Null Deviance:      884.4 
Residual Deviance: 125.8    AIC: 135.8
Analysis of Deviance Table

Model 1: benormal ~ clumpthickness + uniformcellsize + uniformcellshape + 
    margadhesion + epithelial + barenuclei + blandchromatin + 
    normalnucleoli + mitoses
Model 2: benormal ~ clumpthickness + margadhesion + barenuclei + blandchromatin
  Resid. Df Resid. Dev Df Deviance  Pr(&gt;Chi)    
1       673     102.89                          
2       678     125.78 -5  -22.886 0.0003549 ***</code></pre>
<p>Finally, evaluating how accurate model_1 is at prediction by using confusion matrix-</p>
<pre><code>glm.pred   0   1
       0 434  11
       1  10 228</code></pre>
<p>Looking at the confusion matrix this is a very good model with high predictability for both false positives and negatives. The % chance the model falsely predicted cancer when not was 10/444 (2.2%) and the chance the model falsely predicted not having cancer when there was 11/239 (4.6%).</p>
</section>
<section id="decision-tree-and-random-forest-modeling" class="level4">
<h4 class="anchored" data-anchor-id="decision-tree-and-random-forest-modeling">Decision Tree and Random Forest Modeling</h4>
<p>Another modeling technique we used for predicting whether a cell was cancerous or not was a random forest model. One of the biggest advantages of random forests is its versatility. It can be used for both regression and classification tasks, and it’s also easy to view the relative importance it assigns to the input features. One of the biggest problems in machine learning is overfitting, but most of the time this won’t happen thanks to the random forest classifier. If there are enough trees in the forest, the classifier won’t overfit the model.First, we looked at a decision tree model to determine the best split for node splitting. We did this by splitting the data into two sets, training and testing to train the model and then test its accuracy.</p>
<p><strong>Decision Tree Model 1-</strong></p>
<p>For this first model we included all of the variables in the dataset.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="WhatsApp Image 2024-05-05 at 19.10.37.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<pre><code>Residual mean deviance:  0.025 = 8.376 / 335 </code></pre>
<p>Based on this model alone we have a very strong model with a mean squared error (MSE) of just .025.</p>
<p>We then wanted to see if we could make the model better by keeping the residual difference low by pruning the tree and finding the lowest number of nodes to create a split with. Looking at the cross-validated decision tree graph below it looks like splitting the tree using 3 nodes is best.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="WhatsApp Image 2024-05-05 at 19.16.06.jpeg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>After pruning the tree and using 3 nodes to spilt the data below is the resulting model.</p>
<p><img src="WhatsApp Image 2024-05-05 at 19.24.09.jpeg" class="img-fluid"></p>
<pre><code>Residual mean deviance:  0.03891 = 13.15 / 338 </code></pre>
<p>This is another strong model with a MSE of just .039. When comparing these models, their resdidual variances are very similar, as such we would likely choose the more simple model.</p>
<p>Lets now use a random forest model to prevent any potential overfitting of our decision tree model.</p>
<pre><code>Call:
 randomForest(formula = benormal ~ ., data = df_clean, mtry = 3,      importance = TRUE, subset = train) 
               Type of random forest: regression
                     Number of trees: 500
No. of variables tried at each split: 3

          Mean of squared residuals: 0.02729938
                    % Var explained: 88.53
MSE
[1] 0.02557116</code></pre>
<p>By creating a random forest model we were able to reduce the MSE from .039 to .026.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Random Forest.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
<p>Taking a look a which variables were most important in the model.</p>
<p><img src="WhatsApp Image 2024-05-05 at 19.38.23.jpeg" class="img-fluid"></p>
<p>The variable that is important to reduce the mean standard error (MSE) is barenuceli and the variables that were deemed the most important to include in the node splitting were uniformcellsize and uniformcellshape.</p>
<p>Overall, the model is very good with 88.7% of the variables explained. Looking at the confusion matrix:</p>
<pre><code>glm.pred   0   1
       0 438   9
       1   6 230</code></pre>
<p>The percentage, the model falsely predicted cancer when not was 6/444 (1.4%) and the percentage, the model falsely predicted not having cancer when there was 9/239 (3.7%).</p>
</section>
<section id="iii.-limitations" class="level2">
<h2 class="anchored" data-anchor-id="iii.-limitations">iii. Limitations</h2>
<p>There were no major limitations for this analysis but there were a few of things that needed to be done to the dataset in order to clean and make the dataset usable for analysis. First, we had to identify and remove all missing rows from the dataset. Second, we had to transform the response variable to be “0” and “1”. Finally, many of the variables seemed to show a left skew making us question if the variables should be transformed or not.&nbsp;</p>
<p>There were only 699 samples for the dataset and although a solid number of samples, more samples would lead to a more predictable conclusion.&nbsp;</p>
</section>
<section id="iv.-conclusion" class="level2">
<h2 class="anchored" data-anchor-id="iv.-conclusion">iv. Conclusion</h2>
<p>It seems that a significantly accurate model to predict if a cancerous cell could be malignant using the measurements recorded in this dataset. To test this, we created multiple regression models, a random forest model, and a PCA analysis to understand the variables more thoroughly. &nbsp;</p>
<p>In the PCA test we determined that the dataset’s variance could be explained by simplifying and using only 2 of the 9 predictor variables. We then created multiple logistic regression models and compared them to each other to choose the best one. After variable transformation and selection, we determined the best model would be to use all the variables. The percent chance the model falsely predicted cancer when not was 10/444 (2.2%) and the chance the model falsely predicted not having cancer when there was 11/239 (4.6%). We then decided to try and create an optimal best random forest model, starting with a best fit decision tree model. The created model resulted in an overall accuracy rate of almost 98% with the percent chance the model falsely predicted cancer when not was 6/444 (1.4%) and the chance the model falsely predicted not having cancer when there was 9/239 (3.7%). Based on the two models we created, the best model to use would be the random forest model because of its high accuracy and predictability.&nbsp;</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ol type="1">
<li><p>Wolberg,WIlliam. (1992). Breast Cancer Wisconsin (Original). UCI Machine Learning Repository. https://doi.org/10.24432/C5HP4Z.&nbsp;</p></li>
<li><p>Grolemund, G., &amp; Wickham, H. (2011). “Dates and Times Made Easy with lubridate.” <em>Journal of Statistical Software</em>, 40(3), 1-25. [Online]. Available: <a href="https://www.jstatsoft.org/v40/i03/" class="uri">https://www.jstatsoft.org/v40/i03/</a></p></li>
<li><p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2021). <em>ISLR: Data for an Introduction to Statistical Learning with Applications in R</em>. R package version 1.4. [Online]. Available: <a href="https://cran.r-project.org/package=ISLR">https://CRAN.R-project.org/package=ISLR</a></p></li>
<li><p>Kuhn, M. (2008). “Building Predictive Models in R Using the caret Package.” <em>Journal of Statistical Software</em>, 28(5), 1–26. doi:10.18637/jss.v028.i05 [Online]. Available: <a href="https://doi.org/10.18637/jss.v028.i05" class="uri">https://doi.org/10.18637/jss.v028.i05</a></p></li>
<li><p>Liaw, A., &amp; Wiener, M. (2002). “Classification and Regression by randomForest.” <em>R News</em>, 2(3), 18-22. [Online]. Available: <a href="https://cran.r-project.org/doc/Rnews/">https://CRAN.R-project.org/doc/Rnews/</a></p></li>
<li><p>Makowski, D., Lüdecke, D., Patil, I., Thériault, R., Ben-Shachar, M., &amp; Wiernik, B. (2023). “Automated Results Reporting as a Practical Tool to Improve Reproducibility and Methodological Best Practices Adoption.” <em>CRAN</em>. [Online]. Available: <a href="https://easystats.github.io/report/" class="uri">https://easystats.github.io/report/</a></p></li>
<li><p>Miller, T. (2020). <em>leaps: Regression Subset Selection</em>. R package version 3.1. [Online]. Available: <a href="https://cran.r-project.org/package=leaps">https://CRAN.R-project.org/package=leaps</a></p></li>
<li><p>Müller, K., &amp; Wickham, H. (2023). <em>tibble: Simple Data Frames</em>. R package version 3.2.1. [Online]. Available: <a href="https://cran.r-project.org/package=tibble">https://CRAN.R-project.org/package=tibble</a></p></li>
<li><p>R Core Team (2023). <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing, Vienna, Austria. [Online]. Available: <a href="https://www.r-project.org/">https://www.R-project.org/</a></p></li>
<li><p>Ripley, B. (2023). <em>tree: Classification and Regression Trees</em>. R package version 1.0-43. [Online]. Available: <a href="https://cran.r-project.org/package=tree">https://CRAN.R-project.org/package=tree</a></p></li>
<li><p>Sarkar, D. (2008). <em>Lattice: Multivariate Data Visualization with R</em>. Springer, New York. ISBN 978-0-387-75968-5. [Online]. Available: <a href="http://lmdvr.r-forge.r-project.org/">http://lmdvr.r-forge.r-project.org</a></p></li>
<li><p>Sievert, C. (2020). <em>Interactive Web-Based Data Visualization with R, plotly, and shiny</em>. Chapman and Hall/CRC. ISBN 9781138331457. [Online]. Available: <a href="https://plotly-r.com/">https://plotly-r.com</a></p></li>
<li><p>Wickham, H. (2007). “Reshaping Data with the reshape Package.” <em>Journal of Statistical Software</em>, 21(12), 1-20. [Online]. Available: <a href="http://www.jstatsoft.org/v21/i12/" class="uri">http://www.jstatsoft.org/v21/i12/</a></p></li>
<li><p>Wickham, H. (2016). <em>ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. ISBN 978-3-319-24277-4. [Online]. Available: <a href="https://ggplot2.tidyverse.org/">https://ggplot2.tidyverse.org</a></p></li>
<li><p>Wickham, H. (2022). <em>stringr: Simple, Consistent Wrappers for Common String Operations</em>. R package version 1.5.0. [Online]. Available: <a href="https://cran.r-project.org/package=stringr">https://CRAN.R-project.org/package=stringr</a></p></li>
<li><p>Wickham, H. (2023). <em>forcats: Tools for Working with Categorical Variables (Factors)</em>. R package version 1.0.0. [Online]. Available: <a href="https://cran.r-project.org/package=forcats">https://CRAN.R-project.org/package=forcats</a></p></li>
<li><p>Wickham, H., et al.&nbsp;(2019). “Welcome to the tidyverse.” <em>Journal of Open Source Software</em>, 4(43), 1686. doi:10.21105/joss.01686 [Online]. Available: <a href="https://doi.org/10.21105/joss.01686" class="uri">https://doi.org/10.21105/joss.01686</a></p></li>
<li><p>Wickham, H., François, R., Henry, L., Müller, K., &amp; Vaughan, D. (2023). <em>dplyr: A Grammar of Data Manipulation</em>. R package version 1.1.3. [Online]. Available: <a href="https://cran.r-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a></p></li>
<li><p>Wickham, H., &amp; Henry, L. (2023). <em>purrr: Functional Programming Tools</em>. R package version 1.0.2. [Online]. Available: <a href="https://cran.r-project.org/package=purrr">https://CRAN.R-project.org/package=purrr</a></p></li>
<li><p>Wickham, H., Hester, J., &amp; Bryan, J. (2023). <em>readr: Read Rectangular Text Data</em>. R package version 2.1.4. [Online]. Available: <a href="https://cran.r-project.org/package=readr">https://CRAN.R-project.org/package=readr</a></p></li>
<li><p>Wickham, H., Vaughan, D., &amp; Girlich, M. (2023). <em>tidyr: Tidy Messy Data</em>. R package version 1.3.0. [Online]. Available: <a href="https://cran.r-project.org/package=tidyr">https://CRAN.R-project.org/package=tidyr</a></p></li>
<li><p>Revelle, W. (2024). <em>psych: Procedures for Psychological, Psychometric, and Personality Research</em>. Northwestern University, Evanston, Illinois. R package version 2.4.3. [Online]. Available: <a href="https://cran.r-project.org/package=psych">https://CRAN.R-project.org/package=psych</a></p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>